/// The key should be stored only runtime, it doesn't make sense to serialize it since
/// the SparseSet data is not persistent
///
/// Keys can't be used to access other SparseSets, they are only valid for the SparseSet they were
/// created in. Trying to use a key from one SparseSet in another SparseSet can lead to incorrect
/// behavior or panic.
///
/// Every key generated by the same SparseSet is unique, they will not repeat even if the element
/// is removed and a new one is added.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SparseKey {
    pub(crate) sparse_index: usize,
    pub(crate) epoch: usize,
}
